<a href="https://colab.research.google.com/github/nekotanku/colab/blob/master/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##pytorchとは？
pythonベースの科学計算パッケーです。

こんなときに使います。

・GPUのパワーを使用するためのNumpyの代わり

・ディープラーニングの研究プラットフォーム

 ### tensor 

TensorはNumPyのndarrayに似ていますが、GPUでTensorを使用してコンピューティングを高速化することもできます。

In [ ]:
from __future__ import print_function
import torch

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

初期化されていない行列が宣言されていますが、使用する前に既知の明確な値が含まれていません。初期化されていない行列が作成されると、その時点で割り当てられたメモリにあった値が初期値として表示されます。

In [ ]:
#初期化されていない5×3行列を作成
x = torch.empty(5,3)
print(x)

tensor([[1.8947e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [ ]:
#ランダムに初期化した行列を作成
x = torch.rand(5,3)
print(x)

tensor([[0.6974, 0.2901, 0.1622],
        [0.8615, 0.3629, 0.1850],
        [0.2728, 0.5040, 0.4161],
        [0.4144, 0.8773, 0.9312],
        [0.8191, 0.3923, 0.7491]])


In [ ]:
#ゼロで満たされたdtype longの行列を作成
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
#Construct a tensor directly from data:データから直接テンソルを作成
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
#or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
#または、既存のテンソルに基づいてテンソルを作成します。これらのメソッドは、入力テンソルのプロパティを再利用します。 dtype（ユーザーによって新しい値が提供されない限り）
x = x.new_ones(5,3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1179, -0.1495,  2.5041],
        [-0.5842, -0.2309,  0.9329],
        [ 0.6815, -0.5110, -1.6406],
        [-0.2490, -0.8358,  1.5480],
        [ 0.3299, -0.3334, -0.3641]], dtype=torch.float64)


In [ ]:
#Get its size:
#torch.Size is in fact a tuple, so it supports all tuple operations. torch.Sizeは実際にはタプルなので、すべてのタプル操作をサポートします。
print(x.size())

torch.Size([5, 3])


In [ ]:
#操作には複数の構文があります。次の例では、加算演算を見てみましょう。
y = torch.rand(5,3)
print(x + y)

tensor([[ 1.6028,  0.3645,  2.6657],
        [ 0.2628,  0.6963,  1.1542],
        [ 1.2886, -0.3389, -1.1096],
        [ 0.4462, -0.2246,  2.1683],
        [ 0.7264,  0.4491,  0.1941]], dtype=torch.float64)


In [ ]:
#x+yと同じ
print(torch.add(x, y))

tensor([[ 1.6028,  0.3645,  2.6657],
        [ 0.2628,  0.6963,  1.1542],
        [ 1.2886, -0.3389, -1.1096],
        [ 0.4462, -0.2246,  2.1683],
        [ 0.7264,  0.4491,  0.1941]], dtype=torch.float64)


In [ ]:
#引数として出力テンソルを指定
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.6028,  0.3645,  2.6657],
        [ 0.2628,  0.6963,  1.1542],
        [ 1.2886, -0.3389, -1.1096],
        [ 0.4462, -0.2246,  2.1683],
        [ 0.7264,  0.4491,  0.1941]])


In [ ]:
#xをyに追加
#Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
#tensorをインプレースで変更する操作は、_で後置固定されます。たとえば、x.copy_（y）、x.t_（）はxを変更します。
y.add_(x)
print(y)

tensor([[ 1.6028,  0.3645,  2.6657],
        [ 0.2628,  0.6963,  1.1542],
        [ 1.2886, -0.3389, -1.1096],
        [ 0.4462, -0.2246,  2.1683],
        [ 0.7264,  0.4491,  0.1941]])


In [ ]:
print(x[:, 1])

tensor([-0.1495, -0.2309, -0.5110, -0.8358, -0.3334], dtype=torch.float64)


In [ ]:
#tensorのサイズを変更/変更したい場合は、torch.viewを使用できます。
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
#1要素のテンソルがある場合は、.item（）を使用して値をPythonの数値として取得します
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6923])
-0.6923400163650513


## Numpy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze

Torch TensorをNumPy配列に、またはその逆に変換することは簡単です

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

Torch TensorとNumPy配列は、基になるメモリロケーションを共有し（Torch TensorがCPUにある場合）、一方を変更すると他方が変更されます。

### torch tensor を numpy配列に変換

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
#numpy配列の値の変化を確認。元のtensorを変更すると、numpy配列の方も変更される
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### numpy配列を torch tensorに変換

In [ ]:
#CharTensor以外のCPU上のすべてのテンソルは、NumPyへの変換とその逆変換をサポートします。
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


##CUDA Tensors

Tensors can be moved onto any device using the .to method.

テンソルは、.toメソッドを使用して任意のデバイスに移動できます。

CUDAが使えるときにだけやる

In [ ]:
#let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

#AUTOGRAD: AUTOMATIC DIFFERENTIATION

PyTorchのすべてのニューラルネットワークの中心はautogradパッケージです。まず簡単にこれにアクセスしてから、最初のニューラルネットワークのトレーニングに行きます。

autogradパッケージは、Tensorsのすべての操作を自動的に区別します。これは、run-by-runフレームワークです。つまり、バックプロップはコードの実行方法によって定義され、反復ごとに異なる可能性があります。


###tensor

torch.Tensorは、パッケージの中心的なクラスです。その属性.requires_gradをTrueに設定すると、すべての操作の追跡が開始されます。計算が終了したら、.backward（）を呼び出して、すべての勾配を自動的に計算させることができます。このテンソルの勾配は.grad属性に蓄積されます。

テンソルの履歴追跡を停止するには、.detach（）を呼び出してテンソルを計算履歴から切り離し、今後の計算が追跡されないようにします。

履歴を追跡しないようにする（およびメモリを使用する）には、コードブロックを
torch.no_grad（）：でラップすることもできます。モデルはrequire_grad = Trueでトレーニング可能なパラメーターを持っている可能性があるため、モデルを評価するときに特に役立ちますが、勾配は必要ありません。

autogradの実装にとって非常に重要なもう1つのクラス、Functionがあります。

tensorとFunctionは相互に関連していて、計算の完全な履歴をエンコードする非循環グラフを構築します。各テンソルには、テンソルを作成した関数を参照する.grad_fn属性があります（ユーザーが作成したテンソルを除く-grad_fn is None）。

導関数を計算する場合は、Tensorで.backward（）を呼び出すことができます。 Tensorがスカラーの場合（つまり、1つの要素のデータを保持する場合）、backward（）に引数を指定する必要はありません。ただし、要素が多い場合は、一致する形状のテンソルである勾配引数を指定する必要があります。



In [ ]:
#tensorを作成し、requires_grad = Trueを設定して、tensorで計算を追跡します

x = torch.ones(2,2, requires_grad=True)
print(x)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
print(y.grad_fn)

In [ ]:
#Do more operations on y yでさらに操作を行う
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
#.requires_grad_（...）は、既存のTensorのrequire_gradフラグを変更します。入力フラグを指定しない場合、デフォルトでFalseになります。
a = torch.randn(2,2)
a = ((a * 3) / (a -1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


##Grasients

今すぐバックプロップしましょう。 outには単一のスカラーが含まれているため、out.backward（）はout.backward(torch.tensor(1.))と同等です。

In [ ]:
out.backward()

In [ ]:
#Print gradients d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y =y * 2
print(y)

tensor([-232.9169, -609.1898,  799.5416], grad_fn=<MulBackward0>)


この場合、yはスカラーではなくなりました。 torch.autogradは完全なヤコビアンを直接計算できませんでしたが、ベクトル-ヤコビアン積が必要な場合は、単にベクトルを引数として後方に渡します。

In [ ]:
v =torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


torch.no_grad()でコードブロックをラップすることにより、.requires_grad = Trueを使用して、Tensorの履歴の追跡からautogradを停止することもできます。

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [ ]:
#または、.detach（）を使用して、同じ内容で新しいTensorを取得しますが、グラデーションは必要ありません。
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


#Nural networks

ニューラルネットワークは、torch.nnパッケージを使用して構築できます。

autogradを垣間見たところで、nnはautogradに依存してモデルを定義し、モデルを区別しています。 nn.Moduleには、レイヤーと、出力を返すメソッドforward（input）が含まれています。



シンプルなフィードフォワードネットワークです。それは入力を受け取り、それをいくつかの層に次々と送り、最後に出力を与えます。 ニューラルネットワークの一般的なトレーニング手順は次のとおりです。

・いくつかの学習可能なパラメーター（または重み）を持つニューラルネットワークを定義する：Define the neural network that has some learnable parameters (or weights)

・入力のデータセットを反復する　：　Iterate over a dataset of inputs

・ネットワークを介して入力を処理する :  Process input through the network

・損失を計算します（出力が正しいことからどれだけ離れているか）：　Compute the loss (how far is the output from being correct)

・勾配をネットワークのパラメータに反映させる：Propagate gradients back into the network’s parameters

・通常は単純な更新ルールを使用して、ネットワークの重みを更新します。weight= weight-learning_rate * gradient：Update the weights of the network, typically using a simple update rule: weight = weight - learning_rate * gradient





###Define  the Network

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__self():
        super(Net, self).__init__()
        #1つの入力画像チャネル、6つの出力チャネル、3x3の正方形たたみ込み
        self.conv1 = nn.Conv2d(1,6,3)
        #6つの入力画像チャネル,16の出力チャネル、3x3の正方形たたみ込み
        self.conv2 = nn.Conv2d(6,16,3)
        #an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        #max pooling over a (2,2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        #サイズが正方形の場合、指定できる数は1つだけです
        x = F.max_pool2d(F.relu(self.conv2d(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x =F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3
        return x


In [ ]:
a = [93, 110, 124, 125, 128, 130, 132, 135, 136, 151, 178]
import numpy as np
s = np.mean(a)
s

131.0909090909091

In [ ]:
np.median(a)

130.0

In [ ]:
df = pd.DataFrame(a)

In [ ]:
s = df.quantile(0.75)
s

0    135.5
Name: 0.75, dtype: float64