<a href="https://colab.research.google.com/github/nekotanku/colab/blob/master/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install torch torchvision

In [3]:
from  __future__ import print_function
import torch

numpyぽく使えるよ

In [4]:
x = torch.empty(5,3)

In [5]:
print(x)

tensor([[3.7445e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [7]:
x  = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.6693,  1.0099, -1.8113],
        [ 0.4214, -0.0701, -0.1035],
        [-0.2476,  0.1287, -0.2412],
        [ 0.3147, -0.2524,  0.6480],
        [-1.2451,  0.7588,  1.4062]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.9866,  1.8331, -1.7008],
        [ 1.2160,  0.1989,  0.3531],
        [-0.1637,  0.1820, -0.0138],
        [ 0.6664,  0.5375,  1.2822],
        [-0.8974,  1.5407,  2.1351]])


In [15]:
print(torch.add(x, y))

tensor([[ 0.9866,  1.8331, -1.7008],
        [ 1.2160,  0.1989,  0.3531],
        [-0.1637,  0.1820, -0.0138],
        [ 0.6664,  0.5375,  1.2822],
        [-0.8974,  1.5407,  2.1351]])


In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9866,  1.8331, -1.7008],
        [ 1.2160,  0.1989,  0.3531],
        [-0.1637,  0.1820, -0.0138],
        [ 0.6664,  0.5375,  1.2822],
        [-0.8974,  1.5407,  2.1351]])


In [21]:
y.add_(x)
print(y)

#前にある値を変更する今回はy

tensor([[ 0.9866,  1.8331, -1.7008],
        [ 1.2160,  0.1989,  0.3531],
        [-0.1637,  0.1820, -0.0138],
        [ 0.6664,  0.5375,  1.2822],
        [-0.8974,  1.5407,  2.1351]])


In [22]:
print(x[:,1])

tensor([ 1.0099, -0.0701,  0.1287, -0.2524,  0.7588])


テンソルのサイズを変更/再形成する場合は、torch.viewを使用できます。

In [23]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


1要素のテンソルがある場合は、.item（）を使用して値をPython数値として取得します

In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1808])
0.18080326914787292


torch tensorをnumpyに変換することができる

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [27]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [28]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


numpy array を torch tensorに変換

In [29]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor以外のCPU上のすべてのテンソルは、NumPyへの変換およびその逆変換をサポートします。

テンソルは、.toメソッドを使用して任意のデバイスに移動できます。

In [31]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y  = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

numpyで実装

In [37]:
import numpy as np

N, D_in, H, D_out = 64, 1000, 100, 10

x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6

for t in range(500):
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
     
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2


0 27827450.675085563
1 23047512.1286102
2 26408501.71306271
3 35156285.87773135
4 44912608.6769813
5 47197686.36568219
6 35938221.16068861
7 18975838.023840267
8 7611006.375351081
9 2992341.659945527
10 1465510.309538624
11 942773.355566667
12 718831.4501319523
13 590680.0628180453
14 500015.31293420575
15 428860.9777224727
16 370570.6465306819
17 321985.8695470978
18 281004.36770988704
19 246246.68487189873
20 216606.3017529188
21 191174.1814545321
22 169297.12750647188
23 150372.80980143303
24 133922.70753846577
25 119574.30012201123
26 107037.33969829787
27 96033.98507888478
28 86339.40606400289
29 77777.15523110153
30 70194.8973024766
31 63472.590336261615
32 57498.702732310616
33 52174.96791366104
34 47425.0014855611
35 43180.25211820823
36 39368.538026397975
37 35938.77472511236
38 32844.77270134927
39 30051.819253738373
40 27530.789265972053
41 25247.82292724575
42 23177.790036579237
43 21297.536039802904
44 19587.871056844946
45 18031.90355564878
46 16614.424155190733
47 15321.

In [43]:
import torch

dtype = torch.float
device = torch.device("cpu")

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in, device=device, dtype=dtype)
y= torch.randn(N, D_out, device=device, dtype=dtype)

w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

99 429.8313293457031
199 3.7493174076080322
299 0.05901859700679779
399 0.0014679019805043936
499 0.00014888418081682175
